import { useEffect, useRef, useState } from "react";
import { api, QuarantineRecord } from "./lib/api";
import { Badge, Button, Card, ConfirmDialog, ExpandableQuarantineTable, Table, Toast } from "./components/ui";

interface Reconciliation {
  source_total: number;
  target_total: number;
  quarantine_total: number;
  accounted: number;
  matched: boolean;
}

export default function App() {
  const [tab, setTab] = useState(0);
  const tabs = ["Schema Check", "AI Planner", "Dry Run & Quarantine", "Execution & Reconciliation", "History & Rollback"];

  // ---- Global application state ----
  const [currentPlan, setCurrentPlan] = useState<any>(null);
  const [currentPlanId, setCurrentPlanId] = useState<string | null>(null);
  const [isPlanApproved, setIsPlanApproved] = useState(false);
  const [activeRunId, setActiveRunId] = useState<string | null>(null);
  const [dryRunDone, setDryRunDone] = useState(false);
  const [drySummary, setDrySummary] = useState<{ source_count: number; accepted_count: number; rejected_count: number } | null>(null);
  const [reconciliationData, setReconciliationData] = useState<Reconciliation | null>(null);
  const [quarantineRecords, setQuarantineRecords] = useState<QuarantineRecord[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [toast, setToast] = useState<{ message: string; tone: "success" | "error" } | null>(null);
  const toastTimer = useRef<number | undefined>(undefined);
  const [customDataset, setCustomDataset] = useState<{ records: any[]; label: string } | null>(null);

  function notify(message: string, tone: "success" | "error") {
    setToast({ message, tone });
    window.clearTimeout(toastTimer.current);
    toastTimer.current = window.setTimeout(() => setToast(null), 4000);
  }

  async function withLoading<T>(fn: () => Promise<T>): Promise<T | undefined> {
    setIsLoading(true);
    try { return await fn(); }
    catch (e: any) { notify(e.message ?? "Request failed", "error"); return undefined; }
    finally { setIsLoading(false); }
  }

  // ---- Tab 2: AI Planner ----
  async function generatePlan() {
    const res = await withLoading(() => api.generatePlan());
    if (!res) return;
    setCurrentPlan(res.plan);
    setCurrentPlanId(res.plan_id);
    setIsPlanApproved(false);
    setDryRunDone(false);
    setReconciliationData(null);
    notify("Plan generated by AI planner — review it, then approve", "success");
  }

  async function approvePlan() {
    if (!currentPlanId) return;
    const res = await withLoading(() => api.approvePlan(currentPlanId));
    if (!res?.approved) return;
    setIsPlanApproved(true);
    notify("Plan Approved", "success");
    setTab(2); // auto-switch to Dry Run
  }

  // ---- Tab 3: Dry Run ----
  async function runDryRun() {
    const res = await withLoading(() => api.dryRun(undefined, customDataset?.records));
    if (!res) return;
    setActiveRunId(res.run_id);
    setDrySummary(res);
    setDryRunDone(true);
    const q = await withLoading(() => api.quarantine(res.run_id));
    setQuarantineRecords(q?.records ?? []);
    notify(`Dry run complete: ${res.accepted_count} accepted, ${res.rejected_count} quarantined${customDataset ? " (custom dataset)" : " (seed DB)"}`, "success");
  }

  // ---- Tab 4: Execute ----
  const [confirmExecute, setConfirmExecute] = useState(false);
  async function doExecute() {
    setConfirmExecute(false);
    const res = await withLoading(() => api.execute(undefined, undefined, customDataset?.records));
    if (!res) return;
    setActiveRunId(res.run?.run_id ?? activeRunId);
    if (customDataset) {
      const acc = res.run?.accepted_count ?? 0;
      const rej = res.run?.rejected_count ?? 0;
      setReconciliationData({
        source_total: customDataset.records.length,
        target_total: acc,
        quarantine_total: rej,
        accounted: acc + rej,
        matched: acc + rej === customDataset.records.length,
      });
    } else {
      const rec = await withLoading(() => api.reconcile());
      if (rec) setReconciliationData(rec);
    }
    notify("Migration executed", "success");
  }

  // ---- Seed ----
  async function seed() {
    const res = await withLoading(() => api.seed());
    if (res) notify(`Seeded ${res.seeded} source records`, "success");
  }

  const tabsDisabled = [false, false, !isPlanApproved, !dryRunDone, false];

  return (
    <div className="mx-auto max-w-6xl p-6 space-y-6">
      <header className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold">Agentic Data Migration Workbench</h1>
          <p className="text-sm text-muted-foreground">Cloudflare Workers · D1 · Workers AI (llama-3-8b-instruct)</p>
        </div>
        <Button variant="outline" onClick={seed} disabled={isLoading}>{isLoading ? "Processing..." : "Seed DB (1000 rows)"}</Button>
      </header>

      <div className="flex gap-1 border-b border-slate-200">
        {tabs.map((t, i) => (
          <button
            key={t}
            disabled={tabsDisabled[i]}
            onClick={() => setTab(i)}
            title={tabsDisabled[i] ? "Complete the previous step first" : ""}
            className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px ${i === tab ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"} ${tabsDisabled[i] ? "opacity-40 cursor-not-allowed" : ""}`}
          >
            {t}
          </button>
        ))}
      </div>

      {tab === 0 && <SchemaCheckTab isLoading={isLoading} withLoading={withLoading} notify={notify} onCustomDataset={setCustomDataset} customDataset={customDataset} />}

      {tab === 1 && (
        <Card>
          <div className="flex flex-wrap items-center gap-3">
            <Button onClick={generatePlan} disabled={isLoading}>{isLoading ? "Processing..." : "⚡ Generate Plan (AI)"}</Button>
            {isPlanApproved && <Badge tone="green">Plan Approved</Badge>}
          </div>
          <p className="mt-2 text-xs text-muted-foreground">The AI agent inspects both schemas, proposes field mappings with supported transformations, flags incompatible fields, and assigns a risk level. You must approve before Dry Run unlocks.</p>

          {currentPlan && (
            <div className="mt-5 space-y-4">
              <h3 className="font-semibold">Proposed Mapping Rules</h3>
              <Table
                headers={["Source Field", "Target Field", "Transform", "Params"]}
                rows={currentPlan.mappings.map((m: any) => [m.source_field, m.target_field, m.transform, m.params ? JSON.stringify(m.params) : "—"])}
              />
              <div className="text-xs text-muted-foreground">Risk: {currentPlan.risk_assessment ?? "n/a"} · {currentPlan.notes ?? ""}</div>
              <details>
                <summary className="cursor-pointer text-sm font-semibold">Raw AI plan JSON</summary>
                <pre className="mt-2 max-h-60 overflow-auto rounded bg-slate-100 p-3 text-xs">{JSON.stringify(currentPlan, null, 2)}</pre>
              </details>
              <Button onClick={approvePlan} disabled={isLoading || isPlanApproved}>{isPlanApproved ? "Approved ✓" : isLoading ? "Processing..." : "Approve Plan"}</Button>
            </div>
          )}
        </Card>
      )}

      {tab === 2 && (
        <Card>
          {customDataset && (
            <div className="mb-3 flex items-center gap-3 rounded bg-amber-50 p-2 text-xs text-amber-800">
              Running on custom dataset: {customDataset.label} ({customDataset.records.length} rows).
              <Button variant="outline" className="px-2 py-0.5 text-xs" onClick={() => setCustomDataset(null)}>Use Seed DB instead</Button>
            </div>
          )}
          <Button onClick={runDryRun} disabled={isLoading}>{isLoading ? "Processing..." : "Run Dry Run"}</Button>
          {drySummary && (
            <div className="mt-5 grid grid-cols-3 gap-4">
              <Stat label="Source" value={drySummary.source_count} cls="text-blue-600" />
              <Stat label="Accepted" value={drySummary.accepted_count} cls="text-green-600" />
              <Stat label="Rejected (Quarantine)" value={drySummary.rejected_count} cls="text-red-600" />
            </div>
          )}
          {quarantineRecords.length > 0 && (
            <div className="mt-5">
              <h3 className="mb-2 font-semibold">Quarantine Records — click a row to see field errors</h3>
              <ExpandableQuarantineTable records={quarantineRecords} />
            </div>
          )}
        </Card>
      )}

      {tab === 3 && (
        <Card>
          <Button onClick={() => setConfirmExecute(true)} disabled={isLoading || !dryRunDone}>{isLoading ? "Processing..." : "Execute Migration"}</Button>
          {reconciliationData && (
            <div className="mt-5 space-y-3">
              <h3 className="font-semibold">Reconciliation Dashboard</h3>
              <Table
                headers={["Metric", "Count"]}
                rows={[
                  ["Source Total", reconciliationData.source_total],
                  ["Target Total", reconciliationData.target_total],
                  ["Quarantined", reconciliationData.quarantine_total],
                  ["Accounted (Target + Quarantined)", reconciliationData.accounted],
                ]}
              />
              {reconciliationData.matched ? (
                <p className="text-lg font-semibold text-green-600">✅ Green Checkmark — totals reconcile: Source = Target + Quarantined.</p>
              ) : (
                <p className="text-lg font-semibold text-red-600">❌ Red X — mismatch: Source ≠ Target + Quarantined.</p>
              )}
            </div>
          )}
          <ConfirmDialog
            open={confirmExecute}
            title="Confirm Execution"
            message="This will migrate all accepted records into target_contractors. Continue?"
            onConfirm={doExecute}
            onCancel={() => setConfirmExecute(false)}
          />
        </Card>
      )}

      {tab === 4 && <HistoryTab isLoading={isLoading} setIsLoading={setIsLoading} notify={notify} withLoading={withLoading} />}

      <Toast message={toast?.message ?? null} tone={toast?.tone ?? "success"} />
    </div>
  );
}

function Stat({ label, value, cls }: { label: string; value: number; cls: string }) {
  return (
    <div className="rounded-lg border border-slate-200 p-4 text-center">
      <div className={`text-3xl font-bold ${cls}`}>{value}</div>
      <div className="text-xs uppercase tracking-wide text-muted-foreground">{label}</div>
    </div>
  );
}

const DEFAULT_SOURCE_SCHEMA = `{
  "name": "legacy_employee",
  "fields": [
    { "name": "emp_id", "type": "int" },
    { "name": "full_name", "type": "string" },
    { "name": "dept_code", "type": "string" },
    { "name": "hire_date", "type": "string" },
    { "name": "salary", "type": "float" }
  ]
}`;

const DEFAULT_TARGET_SCHEMA = `{
  "name": "modern_contractor",
  "fields": [
    { "name": "contractor_uuid", "type": "uuid" },
    { "name": "first_name", "type": "string" },
    { "name": "last_name", "type": "string" },
    { "name": "department_name", "type": "string" },
    { "name": "start_date", "type": "ISO date" },
    { "name": "hourly_rate", "type": "float" },
    { "name": "status", "type": "string" }
  ]
}`;

const DEFAULT_SAMPLES = `[
  { "emp_id": 1, "full_name": "Alice Smith", "dept_code": "ENG", "hire_date": "2020-03-14", "salary": 95000 },
  { "emp_id": 2, "full_name": "Bob Jones", "dept_code": "SALES", "hire_date": "11/02/2021", "salary": 62000 }
]`;

function SchemaCheckTab({ isLoading, withLoading, notify, onCustomDataset, customDataset }: any) {
  const [sourceSchema, setSourceSchema] = useState(DEFAULT_SOURCE_SCHEMA);
  const [targetSchema, setTargetSchema] = useState(DEFAULT_TARGET_SCHEMA);
  const [samples, setSamples] = useState(DEFAULT_SAMPLES);
  const [report, setReport] = useState<{ valid: boolean; migratable: boolean; errors: string[]; issues: string[] } | null>(null);
  const [example, setExample] = useState<{ total: number; rows: any[] } | null>(null);

  async function validate() {
    let body: any;
    let parsedSamples: any[] = [];
    try {
      parsedSamples = JSON.parse(samples);
      body = {
        source_schema: JSON.parse(sourceSchema),
        target_schema: JSON.parse(targetSchema),
        sample_records: parsedSamples,
      };
    } catch {
      notify("Invalid JSON in one of the inputs", "error");
      return;
    }
    const res = await withLoading(() => api.validateSchema(body));
    if (res) {
      setReport(res);
      if (res.valid) {
        onCustomDataset({ records: parsedSamples, label: `${parsedSamples.length} custom records` });
        notify("Schemas valid — dry run will now use this custom data", "success");
      } else {
        notify("Validation found problems", "error");
      }
    }
  }

  async function loadExample() {
    const res = await withLoading(() => api.exampleDb());
    if (res) setExample(res);
  }

  return (
    <div className="space-y-6">
      <Card>
        <h3 className="font-semibold mb-3">Schema & Mapping Validator</h3>
        <p className="text-xs text-muted-foreground mb-4">Paste a JSON source schema, target schema, and example records. Once valid, the Dry Run and Execute steps will run on <em>this custom data</em>.</p>
        <div className="grid grid-cols-2 gap-4">
          <Field label="Source Schema (JSON)" value={sourceSchema} onChange={setSourceSchema} />
          <Field label="Target Schema (JSON)" value={targetSchema} onChange={setTargetSchema} />
          <Field label="Sample Records (JSON array)" value={samples} onChange={setSamples} />
        </div>
        <div className="mt-4 flex gap-3">
          <Button onClick={validate} disabled={isLoading}>{isLoading ? "Processing..." : "Validate Schemas & Migratability"}</Button>
          <Button variant="outline" onClick={loadExample} disabled={isLoading}>{isLoading ? "Processing..." : "Load Example Seed DB"}</Button>
        </div>

        {report && (
          <div className="mt-5 space-y-2">
            <div className="flex gap-2">
              <Badge tone={report.valid ? "green" : "red"}>{report.valid ? "Schema Valid" : "Schema Invalid"}</Badge>
              <Badge tone={report.migratable ? "green" : "red"}>{report.migratable ? "Migratable" : "Not Migratable"}</Badge>
            </div>
            {report.errors.length > 0 && (
              <ul className="rounded bg-red-50 p-3 text-xs text-red-800 list-disc pl-6">
                {report.errors.map((e, i) => <li key={i}>{e}</li>)}
              </ul>
            )}
            {report.issues.length > 0 && (
              <ul className="rounded bg-amber-50 p-3 text-xs text-amber-800 list-disc pl-6">
                {report.issues.map((e, i) => <li key={i}>{e}</li>)}
              </ul>
            )}
          </div>
        )}
      </Card>

      {example && (
        <Card>
          <h3 className="font-semibold mb-3">Example Seed DB — source_employees ({example.total} total rows, showing 25)</h3>
          <Table
            headers={["emp_id", "full_name", "dept_code", "hire_date", "salary"]}
            rows={example.rows.map((r) => [r.emp_id, r.full_name, r.dept_code, r.hire_date, r.salary])}
          />
        </Card>
      )}
    </div>
  );
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <label className="block text-xs font-semibold">
      {label}
      <textarea
        className="mt-1 w-full h-40 rounded-md border border-slate-300 bg-slate-50 p-2 font-mono text-xs font-normal"
        value={value}
        onChange={(e) => onChange(e.target.value)}
      />
    </label>
  );
}

function HistoryTab({ notify, withLoading }: any) {
  const [runs, setRuns] = useState<any[]>([]);
  const [confirmId, setConfirmId] = useState<string | null>(null);

  async function load() {
    const res = await withLoading(() => api.history());
    if (res) setRuns(res.runs);
  }
  useEffect(() => { load(); }, []);

  async function doRollback() {
    if (!confirmId) return;
    const res = await withLoading(() => api.rollback(confirmId));
    setConfirmId(null);
    if (res?.rolled_back) notify("Migration Rolled Back", "success");
    await load();
  }

  const tone = (s: string | null) => (s === "success" ? "green" : s === "failed" ? "red" : s === "rolled_back" ? "amber" : s === "running" ? "blue" : "slate") as any;

  return (
    <Card>
      <Table
        headers={["Run ID", "Status", "Started", "Total", "Accepted", "Rejected", ""]}
        rows={runs.map((r) => [
          <span className="font-mono text-xs">{r.run_id}</span>,
          <Badge tone={tone(r.status)}>{r.status}</Badge>,
          r.started_at ?? "—",
          r.source_count ?? 0,
          r.accepted_count ?? 0,
          r.rejected_count ?? 0,
          r.status === "success" ? (
            <Button variant="destructive" className="px-3 py-1 text-xs" onClick={() => setConfirmId(r.run_id)}>Rollback</Button>
          ) : "—",
        ])}
      />
      <ConfirmDialog
        open={confirmId !== null}
        title="Confirm Rollback"
        message={`This will delete all migrated rows and quarantined records for run ${confirmId}. Continue?`}
        onConfirm={doRollback}
        onCancel={() => setConfirmId(null)}
      />
    </Card>
  );
}
